### ISSUE TITLE
SyntaxError at line 84

### ISSUE THREAD

**Issue by wildufo** [uhop/install-artifact-from-github#4]
Hello,

All I got is

`npm install --unsafe-perm

> re2@1.15.4 install /root/re2build/node-re2
> install-from-cache --artifact build/Release/re2.node --host-var RE2_DOWNLOAD_MIRROR

/root/re2build/node-re2/node_modules/install-artifact-from-github/bin/install-from-cache.js:84
const isDev = async () => {
                                   ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)`

(I have 0 idea about nodjs.)

**Comment by uhop** [comment]
It looks like your Node is old and doesn't support asynchronous functions. Could you share what version yo use? You can get it by running `node --version`.

**Comment by wildufo** [comment]
Yep it was the node version, took some time by trial and error. Maybe you could add required version to the readme for inexperienced ones like me :)

**Comment by uhop** [comment]
I think that nowadays it is hard to find Node that doesn't support async functions. Even a top-level `await` has been supported since Node 13.3. But I'll add a note to the wiki.
